### ISSUE TITLE
Problem running predict function

### ISSUE THREAD

**Issue by srx3001** [FRED-2/Fred2#236] opened 2020-01-15 12:19 UTC
Dear all, I just started using the Fred2 package for MHC prediction and have followed the tutorial found here:
https://github.com/FRED-2/Fred2/blob/master/Fred2/tutorials/EpitopePrediction.ipynb

The issue when trying to run any predictor. The program seems to break at the external object building.

```
peptides = [Peptide("SYFPEITHI"),Peptide("FIASNGVKL"), Peptide("LLGATCMFV")]
allele = Allele("HLA-A*02:01")
predictor = EpitopePredictorFactory("Syfpeithi")
results = predictor.predict(peptides, alleles=alleles)
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/Fred2/EpitopePrediction/PSSM.py", line 96, in predict
    names=['Seq', 'Method'])
  File "/usr/local/lib/python2.7/dist-packages/pandas/indexes/multi.py", line 939, in from_tuples
    return MultiIndex.from_arrays(arrays, sortorder=sortorder, names=names)
  File "/usr/local/lib/python2.7/dist-packages/pandas/indexes/multi.py", line 889, in from_arrays
    labels, levels = _factorize_from_iterables(arrays)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/categorical.py", line 2068, in _factorize_from_iterables
    return lzip(*[_factorize_from_iterable(it) for it in iterables])
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/categorical.py", line 2040, in _factorize_from_iterable
    cat = Categorical(values, ordered=True)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/categorical.py", line 294, in __init__
    raise TypeError("'values' is not ordered, please "
TypeError: 'values' is not ordered, please explicitly specify the categories order by passing in a categories argument.

I thought it might be the pandas version so I tried with all pandas versions from 0.19 - 0.25, but the error has remained the same.

Is there some dependency I might be missing?

**Comment by christopher-mohr** [comment] 2020-01-15 12:30
Dear @srx3001,

how did you install FRED2?

**Comment by christopher-mohr** [comment] 2020-01-15 13:28
I just noticed that there is an error in your example:

> ```
> peptides = [Peptide("SYFPEITHI"),Peptide("FIASNGVKL"), Peptide("LLGATCMFV")]
> allele = Allele("HLA-A*02:01")
> predictor = EpitopePredictorFactory("Syfpeithi")
> results = predictor.predict(peptides, alleles=alleles)
> ```

It should be ```results = predictor.predict(peptides, alleles=allele) ``` However, I guess that is not the reason for the error message you receive? Unfortunately, I couldn't reproduce your error. The code works fine (after correcting the alleles assignment) in a fresh FRED2 installation using pip.

So I guess it might be helpful if you give us more details on the installation procedure you used.

**Comment by srx3001** [comment] 2020-01-15 13:37
Yeah I fixed the allele part, it was a copy paste error when posting to git.
I used pip for installation, here is some info there:

```
pip --version
pip 19.3.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)

pip show Fred2
Name: Fred2
Version: 2.0.3
Summary: A Framework for Epitope Detection and Vaccine Design
Home-page: https://github.com/Fred-2/Fred2
Author: Benjamin Schubert, Mathias Walzer
Author-email: schubert@informatik.uni-tuebingen.de, walzer@informatik.uni-tuebingen.de
License: BSD
Location: /usr/local/lib/python2.7/dist-packages
Requires: setuptools, pandas, pyomo, svmlight, PyMySQL, biopython, pyVCF
```

If I try to install again using pip I get

```
pip install Fred2
Requirement already satisfied: Fred2 in /usr/local/lib/python2.7/dist-packages (2.0.3)
Requirement already satisfied: setuptools>=18.2 in /usr/lib/python2.7/dist-packages (from Fred2) (20.7.0)
Requirement already satisfied: pandas in /usr/local/lib/python2.7/dist-packages (from Fred2) (0.23.4)
Requirement already satisfied: pyomo>=4.0 in /usr/local/lib/python2.7/dist-packages (from Fred2) (5.6)
Requirement already satisfied: svmlight in /usr/local/lib/python2.7/dist-packages (from Fred2) (0.4)
Requirement already satisfied: PyMySQL in /usr/local/lib/python2.7/dist-packages (from Fred2) (0.9.3)
Requirement already satisfied: biopython in /usr/local/lib/python2.7/dist-packages (from Fred2) (1.73)
Requirement already satisfied: pyVCF in /usr/local/lib/python2.7/dist-packages (from Fred2) (0.6.8)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from pandas->Fred2) (1.16.0)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/lib/python2.7/dist-packages (from pandas->Fred2) (2.7.5)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python2.7/dist-packages (from pandas->Fred2) (2018.9)
Requirement already satisfied: six>=1.4 in /usr/local/lib/python2.7/dist-packages (from pyomo>=4.0->Fred2) (1.12.0)
Requirement already satisfied: appdirs in /usr/local/lib/python2.7/dist-packages (from pyomo>=4.0->Fred2) (1.4.3)
Requirement already satisfied: ply in /usr/local/lib/python2.7/dist-packages (from pyomo>=4.0->Fred2) (3.11)
Requirement already satisfied: PyUtilib>=5.6.4 in /usr/local/lib/python2.7/dist-packages (from pyomo>=4.0->Fred2) (5.6.4)
Requirement already satisfied: nose in /usr/local/lib/python2.7/dist-packages (from PyUtilib>=5.6.4->pyomo>=4.0->Fred2) (1.3.7)
```

**Comment by srx3001** [comment] 2020-01-15 13:43
I just removed it with pip uninstall and reinstalled with 

pip install git+https://github.com/FRED-2/Fred2

Problem is still there with

```
peptides = [Peptide("SYFPEITHI"),Peptide("FIASNGVKL"), Peptide("LLGATCMFV")]
allele = Allele("HLA-A*02:01")
predictor = EpitopePredictorFactory("Syfpeithi")
results = predictor.predict(peptides, alleles=allele)
```

**Comment by christopher-mohr** [comment] 2020-01-15 13:49
Which python version do you use? It works fine in my Conda env using the following versions:

```
pandas                    0.24.2                   pypi_0    pypi
python                    2.7.15            hd51d24c_1009    conda-forge
```

**Comment by srx3001** [comment] 2020-01-16 14:18
So a complete fresh new docker image and your recommended versions of pandas/python resolved the issue.

Thank you for timely help!

Also do you inted to support NetMHCpan 4.0 in the future?

Thanks a lot for your work Fred2 team :)  .

**Comment by christopher-mohr** [comment] 2020-01-16 14:55
Good to hear that it works! 

As far as I know there are currently no plans to support NetMHCpan 4.0. But maybe @b-schubert can comment on this as well.

Of course you can also always contribute to Fred2... :)

**Comment by b-schubert** [comment] 2020-01-16 15:10
If the output format of NetMHCpan 4.0 hasn't changed, it should work out of the box.....

You could try it out by initializing NetMHCpan_3_4 and explicitly pointing to the binary with the ```command``` variable when calling ```.predict()```

Otherwise, you just have to overwrite ```parse_external_result``` of the NetMHCpan_3_4-Class.

**Comment by srx3001** [comment] 2020-01-20 14:45
Speaking of contributing to Fred2, I just finished the class that runs NetMHCpan_4_0, its rather straightforward.

I created the fred_plugin.py file where I declared it as a new class and checked if alleles were the same at http://www.cbs.dtu.dk/services/NetMHCpan-4.0/MHC_allele_names.txt (they are same as 2.8 and 3.0).

Would it help to submit the fred plugin? I can also make a pull request with edited External.py script.

**Comment by christopher-mohr** [comment] 2020-01-21 14:04
Would be perfect if you could make a PR with the edited/extended External.py.

**Comment by christopher-mohr** [comment] 2020-01-31 12:49
@srx3001 could you give us an update on your PR? In best case, we could still include this in the next minor release.

**Comment by srx3001** [comment] 2020-02-03 09:07
I should be able to do it this week.

**Comment by christopher-mohr** [comment] 2020-02-07 11:57
Thanks for contributing to FRED2. 👍 I guess we can close this issue now.

**Closed by christopher-mohr** 2020-02-07 11:57 UTC
